### ISSUE TITLE
Wishlist: global log proxy

### ISSUE THREAD

**Issue by dagolden** [preaction/Log-Any#10]
See Log::Dispatchouli for example.

**Comment by preaction** [comment]
I'm not quite sure what this is about. The synopsis of Log::Dispatchouli seems very similar to just calling `Log::Any->get_logger` for producers. It might be possible to change that to `Log::Any->new`.

Or is this perhaps about changing the adapter configuration so that a consumer can do one thing to configure an adapter and receive a proxy object? In the case where the producer and the consumer are the same code. Something like:

```perl
my @adapter_args = ( 'Stderr' );
my $log = Log::Any->new( @adapter_args ); # Configure adapter and return proxy object
```

**Comment by preaction** [comment]
I'm not sure what this wants, so I'm closing this for now.
