### ISSUE TITLE
Test failures on Windows due to missing Sys::Syslog

### ISSUE THREAD

**Issue by nanis** [preaction/Log-Any#57]
```text
t\00-compile.t .............. 4/15
#   Failed test 'Log/Any/Adapter/Syslog.pm loaded ok'
#   at t\00-compile.t line 57.
#          got: '512'
#     expected: '0'
Can't locate Sys/Syslog.pm in @INC (you may need to install the Sys::Syslog module) (@INC contains: ...
```

and 

```text
t\syslog.t .................. Can't locate Sys/Syslog.pm in @INC (you may need to install the Sys::Syslog module) (@INC contains:  ...
```

These tests should not fail. If `Sys::Syslog is required, it should be specified as a dependency so tools can go fetch it (it builds and installs fine on Windows). If it is optional, tests should expect it might be missing.

With `Sys::Syslog` installed, the tests pass.

**Comment by preaction** [comment]
Sys::Syslog is a core module and has been since Perl 5.0. Is that different for Windows? I can put it in my dependencies, and I think it'll work, but the core Log::Any distribution must not depend on any non-core modules, so if Sys::Syslog isn't actually core despite `corelist Sys::Syslog` saying it is, I have to take it back out...

**Comment by preaction** [comment]
If it turns out that this is a larger problem, I will make this an optional dependency. I'm really loathe to do that, though, because Log::Any should _just work_ on any standard distribution of Perl.

**Comment by nanis** [comment]
I did not actually know that `Sys::Syslog` is a core module -- I just don't remember getting out of the box on Windows, my report was based on a presumption.

Thank you for your work.

**Comment by preaction** [comment]
I mean, it did _fail_, so you don't have the Sys::Syslog module. And there are circumstances (like RedHat's "perl") where this could be a problem, so I absolutely need to declare the dependency (and I have, now, thanks to your report).

I just worry that if this is widespread, if Sys::Syslog is missing on a large percentage of Perls, then my idea to always have the Syslog adapter available to me (because I really recommend using Syslog), isn't the best thing for the users of Log-Any...

**Comment by nanis** [comment]
Got it. I second your recommendation for Syslog and understand your concern.

Thank you very much for your work.
